// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChbc5xjaNOy15eCVE2FQxxwGqNsjnp9fE',
    appId: '1:656448382491:web:7e9483437ae80a0c02babe',
    messagingSenderId: '656448382491',
    projectId: 'unitenalumniapp',
    authDomain: 'unitenalumniapp.firebaseapp.com',
    storageBucket: 'unitenalumniapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0t2zLP_vfVatKvxU-w9Mr7bEZko8HjNU',
    appId: '1:656448382491:android:30a8f29a5f835e8602babe',
    messagingSenderId: '656448382491',
    projectId: 'unitenalumniapp',
    storageBucket: 'unitenalumniapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuVaAe5wonmtcKVP-WKuG02DjM6JvkgvE',
    appId: '1:656448382491:ios:3717b9e66695907f02babe',
    messagingSenderId: '656448382491',
    projectId: 'unitenalumniapp',
    storageBucket: 'unitenalumniapp.appspot.com',
    iosBundleId: 'com.example.unitenAlumniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuVaAe5wonmtcKVP-WKuG02DjM6JvkgvE',
    appId: '1:656448382491:ios:3717b9e66695907f02babe',
    messagingSenderId: '656448382491',
    projectId: 'unitenalumniapp',
    storageBucket: 'unitenalumniapp.appspot.com',
    iosBundleId: 'com.example.unitenAlumniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChbc5xjaNOy15eCVE2FQxxwGqNsjnp9fE',
    appId: '1:656448382491:web:55e242b6ee746f3302babe',
    messagingSenderId: '656448382491',
    projectId: 'unitenalumniapp',
    authDomain: 'unitenalumniapp.firebaseapp.com',
    storageBucket: 'unitenalumniapp.appspot.com',
  );
}
